version: '3'

services:
  wp:
    image: wordpress:5.2-php7.3
    volumes:
      - ./themes/:/var/www/html/wp-content/themes/
      - ./plugins/:/var/www/html/wp-content/plugins/
    env_file:
      - .env
    labels:
      - traefik.backend=wp
      - traefik.frontend.rule=Host:samyerkes.com
      - traefik.docker.network=web
      - traefik.port=80
    networks:
      - internal
      - web

  mysql:
    image: mysql:5.7
    volumes:
      - ./db_data/:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - internal
    labels:
      - traefik.enable=false

networks:
  web:
    external: true
  internal:
    external: false
