version: '3'

services:
  wp:
    image: wordpress:5.2-php7.3
    ports:
      - 8080:80
    volumes:
      - ./themes/:/var/www/html/wp-content/themes/
      - ./plugins/:/var/www/html/wp-content/plugins/
    env_file:
      - .env

  mysql:
    image: mysql:5.7
    ports:
      - 4306:3306
    volumes:
      - ./db_data/:/var/lib/mysql/
    env_file:
      - .env